hugo:
  image: jansanchez/docker-hugo
  volumes:
    - ./source/:/tmp/source
    - ./output/:/tmp/output
  environment:
    - HUGO_BASEURL=http://mobile.frontendlabs.io/
    - HUGO_PORT=80
    - HUGO_THEME=pickles
    - HUGO_WATCH=false

web:
  image: jojomi/nginx-static
  volumes:
    - ./output:/var/www/
  environment:
    - VIRTUAL_HOST=http://mobile.frontendlabs.io/
  ports:
    - 80:80
  restart: always
